version: "2.4"

volumes:
  redical-storage:

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: redical-tests
    depends_on:
      - redis
    entrypoint:
      - sh
      - -c
      - script/test-continuous
    environment:
      - PYTHONASYNCIODEBUG=1
      - REDICAL_REDIS_URI=redis://redis:6379
    restart: on-failure
    tty: true
    volumes:
      - ./:/code:rw

  redis:
    container_name: redical-redis
    image: redis:6.2-alpine
    ports:
      - ${REDICAL_REDIS_PORT:-6379}:6379
    volumes:
      - redical-storage:/data
